version: '3.8'

services:
  visual-dashboard:
    image: python:3.12   # Używamy oficjalnego obrazu Pythona
    container_name: maynard
    ports:
      - "1910:1024"
      - "1999:5000"
    volumes:
      - maynard_data:/mnt  # Wolumen z danymi
      - .:/app             # Montowanie katalogu aplikacji
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]  # Uruchamiamy skrypt startowy

volumes:
  maynard_data:
    external: true
