version: '3.8'

services:
  visual-dashboard:
    build:
      context: ./app
    container_name: maynard
    ports:
      - "1910:1024"
      - "1999:5000"
    volumes:
      - maynard_data:/mnt
    entrypoint: >
      sh -c "mkdir -p /app/analytical-backend/data && cp -r /mnt/. /app/analytical-backend/data/ && python setup.py install && python app.py"
      
volumes:
  maynard_data:
    external: true